# Generated by Django 5.1.7 on 2025-03-18 18:40

import django.core.validators
import django.db.models.deletion
import hr.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default=hr.models.generate_unique_employee_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address', models.TextField()),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='org.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='org.organization')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='org.organization')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('PAYPAL', 'PayPal'), ('DIRECT_DEPOSIT', 'Direct Deposit'), ('MOBILE_PAYMENT', 'Mobile Payment'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, null=True)),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hr.department')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField()),
                ('employment_status', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IN', 'Intern')], default='FT', max_length=2)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('days_off', models.JSONField(blank=True, default=list, null=True)),
                ('annual_leave_days', models.PositiveIntegerField(default=0)),
                ('sick_leave_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_details', to='hr.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_details', to='hr.position')),
            ],
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization'], name='hr_employee_organiz_a34c55_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='hr_employee_last_na_dfcdea_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_employee_per_organization'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization'], name='hr_departme_organiz_2f9086_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='hr_departme_name_00be75_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['manager'], name='hr_departme_manager_97ac8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_department_per_organization'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee'], name='hr_attendan_employe_39518b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='hr_attendan_date_3a46d7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='hr_attendan_status_44ddfc_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='hr_attendan_employe_c63029_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_record_per_day'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('time_out__isnull', True), ('time_out__gt', models.F('time_in')), _connector='OR'), name='time_out_after_time_in'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee'], name='hr_payroll_employe_2cf3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['period_start'], name='hr_payroll_period__4dcc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['period_end'], name='hr_payroll_period__cdc515_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['payment_date'], name='hr_payroll_payment_60be27_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='hr_payroll_status_fd827d_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'period_start', 'period_end'], name='hr_payroll_employe_af56cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('employee', 'period_start', 'period_end'), name='unique_payroll_per_period'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='payroll_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.CheckConstraint(condition=models.Q(('net_salary__gte', 0)), name='net_salary_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.CheckConstraint(condition=models.Q(('overtime_hours__gte', 0)), name='overtime_hours_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.CheckConstraint(condition=models.Q(('overtime_rate__gte', 0)), name='overtime_rate_non_negative'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['department'], name='hr_position_departm_ca3fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['title'], name='hr_position_title_02ea23_idx'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('department', 'title'), name='unique_position_per_department'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('salary_range_max__gte', models.F('salary_range_min'))), name='salary_range_max_gte_min'),
        ),
        migrations.AddIndex(
            model_name='employmentdetails',
            index=models.Index(fields=['employee'], name='hr_employme_employe_fcd686_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdetails',
            index=models.Index(fields=['position'], name='hr_employme_positio_5e2a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdetails',
            index=models.Index(fields=['employment_status'], name='hr_employme_employm_5ae40e_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdetails',
            index=models.Index(fields=['hire_date'], name='hr_employme_hire_da_9c81ae_idx'),
        ),
    ]
